41 timelin grid
chell-uoxou/watnow-hackathon-2024-team3 pull request #43
Opened 2024-10-08 01:09 UTC by Mimimi19

タイムテーブルの作成
import { Timeline } from "~/features/timeline/Timeline";

  return (
    <div className="flex w-2/3 ">
      <Timeline itemHeight={100} interval={0.25} />
    </div>
  );

で実行可能

2024-10-08 01:12 UTC, Mimimi19 commented
タイムテーブルの作成
import { Timeline } from "~/features/timeline/Timeline";

return (
　<Timeline itemHeight={100} interval={0.25} />
);
で実行可能

って書きたかった感じです

2024-10-09 22:12 UTC, chell-uoxou commented
@Mimimi19 
① 右上の・・・からコメントの編集できます！
② markdownに対応しているので、\```で囲むとコードブロックにできて、
```typescript
import { Timeline } from "~/features/timeline/Timeline";

return (
　
);
```
みたいな感じに綺麗に表示できます。

わからなかったらこのボタンを押してもできると思います！
<img width="347" alt="image" src="https://github.com/user-attachments/assets/be0b9df6-79cb-4693-93d1-6302c242ca4c">

2024-10-12 04:46 UTC, chell-uoxou requested changes

2024-10-12 04:46 UTC, chell-uoxou commented on frontend/src/features/timeLine/components/TimelineGridLine.tsx
> +  // テイルウィンドウに用いいる他目のitemHeight　pxの生成
//グリッドのdivの高さ

2024-10-12 04:46 UTC, chell-uoxou commented on frontend/src/features/timeLine/components/TimelineGridLine.tsx
> +        {props.minutes === 0 ? "00" : props.minutes}
https://zenn.dev/captain_blue/articles/zero-padding-in-javascript

これがよさそう

2024-10-12 04:46 UTC, chell-uoxou commented on frontend/src/features/timeLine/components/TimelineGridLine.tsx
> +          "flex-1 flex w-full translate-y-2 border-t-2 border-brand-border-color border-dashed"
点線は1pxでよさそうです！

2024-10-12 04:46 UTC, chell-uoxou commented on frontend/src/app/practice/test1/page.tsx
別ファイル作ってもらって！

2024-10-12 04:46 UTC, chell-uoxou commented on frontend/src/features/timeline/Timeline.tsx
> +  function getDividedMinutes(intervalType: 1 | 0.5 | 0.25): number[] {
intervalTypeの型は再定義するより上で定義した型を参照する方が保守性が高い（あとで編集しやすい）です！

したがって
```typescript
intervalType: TimelineProps["interval"]
```
とするといいとよさそう

2024-10-12 05:04 UTC, chell-uoxou commented on frontend/src/app/practice/test1/page.tsx
> +export default function test1() {
Page()でいいっす！

2024-10-12 05:10 UTC, chell-uoxou approved these changes
LGTM!

2024-10-12 05:10 UTC, chell-uoxou commented on frontend/src/app/practice/test3/page.tsx
> +export default function test3() {
Page()で

2024-10-12 05:11 UTC, merged